### ISSUE TITLE
Cannot install deps

### ISSUE THREAD

**Issue by samhh** [samhh/portfolio2019#3]
Fails on a post-install script:

```
$ yarn install --verbose
[...]
verbose 60.459416018 Error: <path>/portfolio2019/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: <path>/portfolio2019/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.8.0 runtime=node arch=x64 libc= platform=linux)
/bin/sh: node-gyp: command not found
    at ProcessTermError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:25884:17)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:673:12)
error /home/sam/dev/portfolio2019/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: <path>/portfolio2019/node_modules/sharp
Output:
```

Tried and failed:

- Remove lockfile and bump all deps to latest in npm manifest
- Install `libvips` package
- Wipe `~/.npm/_libvips/`
- Run `yarn cache clean`

**Comment by samhh** [comment]
Solution: install `node-gyp`. I installed it from the Arch package repository, but users on other systems should be able to get by with `yarn add global node-gyp` or `npm i -g node-gyp`.

**Comment by samhh** [comment]
Actually, for Arch users, a better solution is to install `npm`, which is generally expected on any system with `node`. It has a dependency upon `node-gyp`.
